apiVersion: brain.io/direct
kind: DB
metadata:
  name: brain-pg
  namespace: brain-system
  labels:
    region: 192.168.12.53.nip.io
spec:
  projectId: brain-system
  engine: postgresql
  exposeNodePort: true
  quota: xs
  replicas: 1
  terminationPolicy: Delete

