apiVersion: brain.io/direct
kind: AP
metadata:
  name: sealai-api-staging
  namespace: brain-system
  labels:
    region: 192.168.12.53.nip.io
spec:
  projectId: brain-system
  input:
    image: aimerite/sealai-api:latest
    imagePullPolicy: Always
    env:
      - name: VMSELECT_URL
        valueFrom:
          secretKeyRef:
            key: VMSELECT_URL
            name: sealai-api-staging-env
      - name: VLSELECT_URL
        valueFrom:
          secretKeyRef:
            key: VLSELECT_URL
            name: sealai-api-staging-env
      - name: SEALOS_DESKTOP_URL
        valueFrom:
          secretKeyRef:
            key: SEALOS_DESKTOP_URL
            name: sealai-api-staging-env
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            key: DATABASE_URL
            name: sealai-api-staging-env
      - name: DB_PUBLIC_HOST
        valueFrom:
          secretKeyRef:
            key: DB_PUBLIC_HOST
            name: sealai-api-staging-env
      - name: WHODB_URL
        valueFrom:
          secretKeyRef:
            key: WHODB_URL
            name: sealai-api-staging-env
      - name: SEALOS_DESKTOP_SKIP_TLS_VERIFY
        value: "1"
    network:
      privatePort: 9000
      platformAddresses:
        - id: pa_stagingapi1
          port: 9000
        - id: pa_stagingapi2
          port: 9000
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 9000
        initialDelaySeconds: 15
        periodSeconds: 10
      readiness:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 9000
        initialDelaySeconds: 5
        periodSeconds: 5
      startup:
        failureThreshold: 30
        httpGet:
          path: /health
          port: 9000
        periodSeconds: 5
  paused: false
  resource:
    limits:
      cpu: 1000m
      memory: 1024Mi
    replicas: 1
    requests:
      cpu: 250m
      memory: 512Mi
