{{- if .Values.api.enabled }}
apiVersion: brain.io/direct
kind: AP
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brain-system.labels" . | nindent 4 }}
    {{- include "brain-system.regionLabel" . | nindent 4 }}
  {{- with (include "brain-system.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  projectId: {{ .Values.projectId | default .Release.Namespace | quote }}
  input:
    image: {{ .Values.api.image | quote }}
    imagePullPolicy: {{ .Values.api.imagePullPolicy }}
    env:
      {{- range $key, $_ := .Values.api.env }}
      {{- include "brain-system.secretEnvRef" (dict "name" $key "secretName" $.Values.secrets.apiName "optional" false) | nindent 6 }}
      {{- end }}
      {{- range $key, $value := .Values.api.staticEnv }}
      {{- include "brain-system.envValue" (dict "name" $key "value" $value) | nindent 6 }}
      {{- end }}
    network:
      privatePort: {{ .Values.api.port }}
      platformAddresses:
        {{- toYaml .Values.api.platformAddresses | nindent 8 }}
    probes:
      {{- toYaml .Values.api.probes | nindent 6 }}
  paused: {{ .Values.api.paused }}
  restartRequest: {{ .Values.api.restartRequest }}
  resource:
    replicas: {{ .Values.api.resources.replicas }}
    requests:
      {{- toYaml .Values.api.resources.requests | nindent 6 }}
    limits:
      {{- toYaml .Values.api.resources.limits | nindent 6 }}
{{- end }}
