{{- if .Values.registry.enabled }}
apiVersion: brain.io/direct
kind: AP
metadata:
  name: {{ .Values.registry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brain-system.labels" . | nindent 4 }}
    {{- include "brain-system.regionLabel" . | nindent 4 }}
  {{- with (include "brain-system.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  projectId: {{ .Values.projectId | default .Release.Namespace | quote }}
  input:
    image: {{ .Values.registry.image | quote }}
    imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
    network:
      privatePort: {{ .Values.registry.port }}
      platformAddresses:
        {{- toYaml .Values.registry.platformAddresses | nindent 8 }}
  paused: {{ .Values.registry.paused }}
  restartRequest: {{ .Values.registry.restartRequest }}
  resource:
    replicas: {{ .Values.registry.resources.replicas }}
    requests:
      {{- toYaml .Values.registry.resources.requests | nindent 6 }}
    limits:
      {{- toYaml .Values.registry.resources.limits | nindent 6 }}
{{- end }}
